name: PR Render

on:
  pull_request

jobs:
  render-docs:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: ğŸ¦„ Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.16.1'

      - name: âš™ï¸ Install dependencies
        run: npm install

      - name: ğŸ“ Render docs
        run: npm run render-artifacts

      - name: â¬†ï¸ Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rendered-pull-request
          path: output/
